version: 0.2
run-as: root

phases:

  install:
    commands:
      - echo Installing app dependencies...
      - echo 'Check kubectl version'
      - kubectl version --short --client
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME
  build:
    commands:
      - kubectl rollout restart deploy keygenerator -n dev-ms
